#!/bin/bash
#SBATCH --job-name=FIS_1
#SBATCH --time=00:10:00                 # Maximum time (HH:MM:SS)
#SBATCH --ntasks=32                      # run on a single CPU
#SBATCH --mem=100mb                       # reserve 1GB memory for job
#SBATCH --output=./1_3.log                 # standard output and error log
#SBATCH --partition=teach               # run in the teaching queue

echo 1
./forbidden_island_simulation -g 800000 -t 1
