#!/bin/bash
#SBATCH --job-name=FIS_26
#SBATCH --time=00:10:00                 # Maximum time (HH:MM:SS)
#SBATCH --ntasks=32                      # run on a single CPU
#SBATCH --mem=100mb                       # reserve 1GB memory for job
#SBATCH --output=./26.log                 # standard output and error log
#SBATCH --partition=teach               # run in the teaching queue
#SBATCH --nodes=1

echo 26
./forbidden_island_simulation -g 800000 -t 26
