#!/bin/bash
#SBATCH --job-name=FIS_27
#SBATCH --time=00:10:00                 # Maximum time (HH:MM:SS)
#SBATCH --ntasks=32                      # run on a single CPU
#SBATCH --mem=100mb                       # reserve 1GB memory for job
#SBATCH --output=./logs/27.log                 # standard output and error log
#SBATCH --partition=teach               # run in the teaching queue
#SBATCH --nodes=1

echo 27
./forbidden_island_simulation -g 5000000 -t 27
